let data = `
  1|#||4|545|updatePanel|ctl00_PlaceHolderMain_UpdatePanel4|<select name="ctl00$PlaceHolderMain$ddlStudySystem" onchange="javascript:setTimeout(&#39;__doPostBack(\&#39;ctl00$PlaceHolderMain$ddlStudySystem\&#39;,\&#39;\&#39;)&#39;, 0)" id="ctl00_PlaceHolderMain_ddlStudySystem" disabled="disabled" class="control-dropdownlist" style="width:100%;">
       <option value="-99">-- اختر --</option>
       <option selected="selected" value="1">منتظم</option>
       <option value="2">منتسب كلي</option>
       <option value="3">منتسب جزئي</option>
       <option value="5">كبيرات</option>
       <option value="7">مدمج</option>
  
  </select>|364|updatePanel|ctl00_PlaceHolderMain_UpdatePanel1|<select name="ctl00$PlaceHolderMain$ddlClass" onchange="javascript:setTimeout(&#39;__doPostBack(\&#39;ctl00$PlaceHolderMain$ddlClass\&#39;,\&#39;\&#39;)&#39;, 0)" id="ctl00_PlaceHolderMain_ddlClass" class="control-dropdownlist" style="width:100%;">
       <option value="-99">-- اختر --</option>
       <option selected="selected" value="23">مستوى ثالث</option>
  
  </select>|373|updatePanel|ctl00_PlaceHolderMain_UpdatePanel2|<select name="ctl00$PlaceHolderMain$ddlSpecialty" onchange="javascript:setTimeout(&#39;__doPostBack(\&#39;ctl00$PlaceHolderMain$ddlSpecialty\&#39;,\&#39;\&#39;)&#39;, 0)" id="ctl00_PlaceHolderMain_ddlSpecialty" class="control-dropdownlist" style="width:100%;">
       <option value="-99">-- اختر --</option>
       <option selected="selected" value="25">قسم عام</option>
  
  </select>|360|updatePanel|ctl00_PlaceHolderMain_UpdatePanel12|<select name="ctl00$PlaceHolderMain$ddlSection" onchange="javascript:setTimeout(&#39;__doPostBack(\&#39;ctl00$PlaceHolderMain$ddlSection\&#39;,\&#39;\&#39;)&#39;, 0)" id="ctl00_PlaceHolderMain_ddlSection" class="control-dropdownlist" style="width:100%;">
       <option value="-99">-- الكل --</option>
       <option selected="selected" value="8">8</option>
  
  </select>|2389|updatePanel|ctl00_PlaceHolderMain_oUpdatePanelStudent|<select name="ctl00$PlaceHolderMain$ddlStudent" onchange="javascript:setTimeout(&#39;__doPostBack(\&#39;ctl00$PlaceHolderMain$ddlStudent\&#39;,\&#39;\&#39;)&#39;, 0)" id="ctl00_PlaceHolderMain_ddlStudent" class="control-dropdownlist" style="width:100%;">
       <option value="-99">-- اختر --</option>
       <option value="29708874,12661819">يوسف عمر احمد باهيثم</option>
       <option value="28345232,12661819">محمد عبدالله محمد الزبيدى</option>
       <option selected="selected" value="28503833,12661819">نورة ماهر حمدان الصبحي</option>
       <option value="29149463,12661819">غنى ماهر صالح السلمى</option>
       <option value="28528352,12661819">محمد رائد بن سمير مؤمنه</option>
       <option value="29215371,12661819">محمد علي - الهاشمي</option>
       <option value="28307438,12661819">عبد الرحمن احمد عبد الرحمن الجويبري</option>
       <option value="28224629,12661819">رندا رائد عبدالرحمن بخارى</option>
       <option value="29098795,12661819">أنس ماجد سامى الشريف</option>
       <option value="25527307,12661819">رتيل عمرو عبدالرحيم بخاري</option>
       <option value="28253468,12661819">ريم مشاري محمد اللهيبي</option>
       <option value="28339191,12661819">ريم احمد عيسى دوش</option>
       <option value="28240381,12661819">بتال غازي يحي الحربي</option>
       <option value="28255696,12661819">زياد سامى حامد الصبحى</option>
       <option value="28273386,12661819">بشاير ياسر ابن سعيد الغامدى</option>
       <option value="25362656,12661819">اياد ريان محمود فادان</option>
       <option value="28395391,12661819">يولاند محمد سمير مجلد</option>
       <option value="29084175,12661819">مها حامد بن عبدالعزيز صباغ</option>
       <option value="28201473,12661819">سارة سعد محمد الزهراني</option>
       <option value="28274501,12661819">شموخ محمد عبدالله المقاطي</option>
       <option value="28329379,12661819">شادن تركى سليمان الحربي</option>
       <option value="28499276,12661819">مسك فيصل حامد المجنوني</option>
       <option value="29131929,12661819">لمار سلطان احمد محمد</option>
       <option value="28370880,12661819">كادي عبدالمحسن سالم المحمادي</option>
       <option value="28326004,12661819">ماهر بدر بن عاتق الحربي</option>
       <option value="29385485,12661819">تالين مشاري احمد السلمي</option>
       <option value="28478661,12661819">ياسر مروان بن عيسى سمندر</option>
       <option value="29242995,12661819">كنان عادل صدقه عتيق</option>
       <option value="29255669,12661819">رانسي عادل عوض البشري</option>
       <option value="28453054,12661819">فهد منصور سعيد الغامدي</option>
  
  </select>|512|updatePanel|ctl00_PlaceHolderMain_oUpdatePanelUnitType|<select name="ctl00$PlaceHolderMain$ddlUnitTypesDDL" onchange="javascript:setTimeout(&#39;__doPostBack(\&#39;ctl00$PlaceHolderMain$ddlUnitTypesDDL\&#39;,\&#39;\&#39;)&#39;, 0)" id="ctl00_PlaceHolderMain_ddlUnitTypesDDL" class="control-dropdownlist" style="width:100%;">
       <option selected="selected" value="-99">-- الكل --</option>
       <option value="1">وحد تعلمية مفصلة</option>
       <option value="2">نمائي</option>
       <option value="3">وحد تعلمية موجزة</option>
       <option value="4">نشاط لا صفي</option>
  
  </select>|819|updatePanel|ctl00_PlaceHolderMain_UpdatePanel3|<select name="ctl00$PlaceHolderMain$ddlUnit" onchange="javascript:setTimeout(&#39;__doPostBack(\&#39;ctl00$PlaceHolderMain$ddlUnit\&#39;,\&#39;\&#39;)&#39;, 0)" id="ctl00_PlaceHolderMain_ddlUnit" class="control-dropdownlist" style="width:100%;">
       <option value="-99">-- اختر --</option>
       <option value="616259,0">مجال تعلم الرياضيات</option>
       <option selected="selected" value="616257,0">مجال تعلم التربية الإسلامية</option>
       <option value="616268,0">مجال الصحة والتطور البدني</option>
       <option value="616258,0">مجال تعلم اللغة العربية</option>
       <option value="616256,0">مجال التطور الاجتماعي- العاطفي</option>
       <option value="616260,0">مجال تعلم العلوم</option>
       <option value="616266,0">مجال تعلم الوطنية والتربية الاجتماعية</option>
       <option value="616267,0">مجال تعلم الفنون الإبداعية</option>
  
  </select>|499|updatePanel|ctl00_PlaceHolderMain_UpdatePanel6|<ul><li><input type="submit" name="ctl00$PlaceHolderMain$ibtnSearch" value="ابحث" onclick="javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$PlaceHolderMain$ibtnSearch&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, false))" id="ctl00_PlaceHolderMain_ibtnSearch" title="ابحث" class="btnstyle" /></li><li><input type="submit" name="ctl00$PlaceHolderMain$ibtnBack" value="عودة" id="ctl00_PlaceHolderMain_ibtnBack" title="عودة" class="btnstyle" /></li></ul>|972|updatePanel|ctl00_PlaceHolderMain_UpdatePanel9|<table id="ctl00_PlaceHolderMain_tblPrinterFriendlyMsg" style="width: 98%;">
       <tr>
               <td><table><tr><td unselectable="on"><span id="ctl00_PlaceHolderMain_lblPrinterFriendlyMsg" class="StandardFont">لعرض صفحة قابلة للطباعة،</span></td><td><a onclick="return GetImagesPassFlagsValuesAndConfirm(&#39;ستتم عملية حفظ نتائج المهارة للطفل، هل أنت متأكد من الاستمرار؟&#39;,&#39;ctl00_lblMSG&#39;,&#39;ctl00_ibtnYes&#39;,&#39;ctl00_ibtnNo&#39;,&#39;ctl00_ibtnClose&#39;,&#39;ctl00_lblConfirmTitleText&#39;,&#39;تأكيد عملية الحفظ&#39;,&#39;SaveAndPrint&#39;,&#39;450&#39;,&#39;120&#39;,&#39;&#39;);" id="ctl00_PlaceHolderMain_lbtnClickHere" title="انقر هنا." class="StandardFont" href="javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$PlaceHolderMain$lbtnClickHere&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, true))">انقر هنا.</a></td></tr></table></td>
               <td id="ctl00_PlaceHolderMain_Td1" align="left"></td>
       </tr>
  </table>
  |20505|updatePanel|ctl00_PlaceHolderMain_UpdatePanel7|<table id="ctl00_PlaceHolderMain_tblGvInsertSkillByStudentAndUnit" width="100%">
       <tr>
               <td><div>
                       <table class="GridClass" cellspacing="0" rules="all" border="1" id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit" style="border-color:BurlyWood;width:100%;border-collapse:collapse;">
                               <tr class="tableHeaderCell" align="right">
                                       <th scope="col"><a href="javascript:__doPostBack(&#39;ctl00$PlaceHolderMain$gvInsertSkillByStudentAndUnit&#39;,&#39;Sort$SkillDesc&#39;)">المعارف والمهارات والقدرات</a> <img src="/Noor/WebResource.axd?d=1Z74HDst0KZ4d3RAxG2zTFOuzG0MVATTLSPneNWK_N8Sl34r4aku8eS8B1YjZ9N1dkJysXmM3mBszBqBrs2MzxEYh3H0fYXQX00Yqf5VwkQ9Fi1pvwz2S_v8KrFUBYyDry8jqBXXD6ETeyjJPKUaWIHwHxuIs_TxaDwz914Ee1muY1OP0&amp;t=636844669760000000" style="border-width:0px;" /></th><th align="center" scope="col"><table><tr><td><span id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl01_lblPassHeader" class="LabelHeaderCell">التقييم</span></td></tr><tr><td><table id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl01_rblSkillResultIDs" onclick="ChangeAllImagesURL(&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit&#39;,this,&#39;imgSkillResult&#39;);" border="0">
                                               <tr>
                                                       <td><input id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl01_rblSkillResultIDs_0" type="radio" name="ctl00$PlaceHolderMain$gvInsertSkillByStudentAndUnit$ctl01$rblSkillResultIDs" value="1" checked="checked" /><label for="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl01_rblSkillResultIDs_0">أتقن</label></td><td><input id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl01_rblSkillResultIDs_1" type="radio" name="ctl00$PlaceHolderMain$gvInsertSkillByStudentAndUnit$ctl01$rblSkillResultIDs" value="2" /><label for="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl01_rblSkillResultIDs_1">لم يتقن</label></td><td><input id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl01_rblSkillResultIDs_2" type="radio" name="ctl00$PlaceHolderMain$gvInsertSkillByStudentAndUnit$ctl01$rblSkillResultIDs" value="3" /><label for="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl01_rblSkillResultIDs_2">إلى حد ما</label></td><td><input id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl01_rblSkillResultIDs_3" type="radio" name="ctl00$PlaceHolderMain$gvInsertSkillByStudentAndUnit$ctl01$rblSkillResultIDs" value="-99" /><label for="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl01_rblSkillResultIDs_3">غير محدد</label></td>
                                               </tr>
                                       </table></td></tr></table></th><th align="center" scope="col">ملاحظات</th>
                               </tr><tr id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl02" class="StandardFontPlain" align="right" ID="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl02" onmouseout="document.getElementById(&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl02&#39;).style.backgroundColor =  &#39;&#39;;" onmouseover="document.getElementById(&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl02&#39;).style.backgroundColor =  &#39;#daf3f0&#39;;">
                                       <td>ربط أذكار اليوم والليلة بسور القرآن وأحاديث الرسول صلى الله وعليه وسلم</td><td align="center" onclick="ChangeThisImagesURL(&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit&#39;,&#39;rblSkillResultIDs&#39;,&#39;imgSkillResult&#39;,&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl02_imgSkillResult&#39;);" style="width:280px;"><img id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl02_imgSkillResult" title="أتقن" SkillID="710717" RowIndex="0" hdnSrc="~/images/Common/True.png" src="../images/Common/True.png" style="height:20px;width:20px;border-width:0px;" /></td><td align="center" style="width:400px;"><input name="ctl00$PlaceHolderMain$gvInsertSkillByStudentAndUnit$ctl02$tbTeacherNotes" type="text" maxlength="255" id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl02_tbTeacherNotes" class="StandardFontPlain" style="width:400px;" /></td>
                               </tr><tr id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl03" class="StandardFontPlain" align="right" ID="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl03" onmouseout="document.getElementById(&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl03&#39;).style.backgroundColor =  &#39;&#39;;" onmouseover="document.getElementById(&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl03&#39;).style.backgroundColor =  &#39;#daf3f0&#39;;">
                                       <td>يتحدّث بلغة مناسبة عن نسب النبي صلى الله عليه وسلم</td><td align="center" onclick="ChangeThisImagesURL(&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit&#39;,&#39;rblSkillResultIDs&#39;,&#39;imgSkillResult&#39;,&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl03_imgSkillResult&#39;);" style="width:280px;"><img id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl03_imgSkillResult" title="أتقن" SkillID="710725" RowIndex="1" hdnSrc="~/images/Common/True.png" src="../images/Common/True.png" style="height:20px;width:20px;border-width:0px;" /></td><td align="center" style="width:400px;"><input name="ctl00$PlaceHolderMain$gvInsertSkillByStudentAndUnit$ctl03$tbTeacherNotes" type="text" maxlength="255" id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl03_tbTeacherNotes" class="StandardFontPlain" style="width:400px;" /></td>
                               </tr><tr id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl04" class="StandardFontPlain" align="right" ID="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl04" onmouseout="document.getElementById(&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl04&#39;).style.backgroundColor =  &#39;&#39;;" onmouseover="document.getElementById(&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl04&#39;).style.backgroundColor =  &#39;#daf3f0&#39;;">
                                       <td>يتعرف على مفهوم الصلاة وأركانها وعدد مرات الصلاة وعدد ركعاتها</td><td align="center" onclick="ChangeThisImagesURL(&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit&#39;,&#39;rblSkillResultIDs&#39;,&#39;imgSkillResult&#39;,&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl04_imgSkillResult&#39;);" style="width:280px;"><img id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl04_imgSkillResult" title="أتقن" SkillID="710723" RowIndex="2" hdnSrc="~/images/Common/True.png" src="../images/Common/True.png" style="height:20px;width:20px;border-width:0px;" /></td><td align="center" style="width:400px;"><input name="ctl00$PlaceHolderMain$gvInsertSkillByStudentAndUnit$ctl04$tbTeacherNotes" type="text" maxlength="255" id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl04_tbTeacherNotes" class="StandardFontPlain" style="width:400px;" /></td>
                               </tr><tr id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl05" class="StandardFontPlain" align="right" ID="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl05" onmouseout="document.getElementById(&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl05&#39;).style.backgroundColor =  &#39;&#39;;" onmouseover="document.getElementById(&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl05&#39;).style.backgroundColor =  &#39;#daf3f0&#39;;">
                                       <td>يذكر أن مكة قبلة المسلمين</td><td align="center" onclick="ChangeThisImagesURL(&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit&#39;,&#39;rblSkillResultIDs&#39;,&#39;imgSkillResult&#39;,&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl05_imgSkillResult&#39;);" style="width:280px;"><img id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl05_imgSkillResult" title="أتقن" SkillID="710718" RowIndex="3" hdnSrc="~/images/Common/True.png" src="../images/Common/True.png" style="height:20px;width:20px;border-width:0px;" /></td><td align="center" style="width:400px;"><input name="ctl00$PlaceHolderMain$gvInsertSkillByStudentAndUnit$ctl05$tbTeacherNotes" type="text" maxlength="255" id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl05_tbTeacherNotes" class="StandardFontPlain" style="width:400px;" /></td>
                               </tr><tr id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl06" class="StandardFontPlain" align="right" ID="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl06" onmouseout="document.getElementById(&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl06&#39;).style.backgroundColor =  &#39;&#39;;" onmouseover="document.getElementById(&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl06&#39;).style.backgroundColor =  &#39;#daf3f0&#39;;">
                                       <td>يذكر بعض معاني السور القرآنية القصيرة والآيات ذات الدلالة على بعض المفاهيم</td><td align="center" onclick="ChangeThisImagesURL(&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit&#39;,&#39;rblSkillResultIDs&#39;,&#39;imgSkillResult&#39;,&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl06_imgSkillResult&#39;);" style="width:280px;"><img id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl06_imgSkillResult" title="أتقن" SkillID="710715" RowIndex="4" hdnSrc="~/images/Common/True.png" src="../images/Common/True.png" style="height:20px;width:20px;border-width:0px;" /></td><td align="center" style="width:400px;"><input name="ctl00$PlaceHolderMain$gvInsertSkillByStudentAndUnit$ctl06$tbTeacherNotes" type="text" maxlength="255" id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl06_tbTeacherNotes" class="StandardFontPlain" style="width:400px;" /></td>
                               </tr><tr id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl07" class="StandardFontPlain" align="right" ID="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl07" onmouseout="document.getElementById(&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl07&#39;).style.backgroundColor =  &#39;&#39;;" onmouseover="document.getElementById(&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl07&#39;).style.backgroundColor =  &#39;#daf3f0&#39;;">
                                       <td>يذكر معاني بعض السور القرآنية القصيرة والآيات ذات الدلالة على بعض المفاهيم</td><td align="center" onclick="ChangeThisImagesURL(&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit&#39;,&#39;rblSkillResultIDs&#39;,&#39;imgSkillResult&#39;,&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl07_imgSkillResult&#39;);" style="width:280px;"><img id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl07_imgSkillResult" title="أتقن" SkillID="710719" RowIndex="5" hdnSrc="~/images/Common/True.png" src="../images/Common/True.png" style="height:20px;width:20px;border-width:0px;" /></td><td align="center" style="width:400px;"><input name="ctl00$PlaceHolderMain$gvInsertSkillByStudentAndUnit$ctl07$tbTeacherNotes" type="text" maxlength="255" id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl07_tbTeacherNotes" class="StandardFontPlain" style="width:400px;" /></td>
                               </tr><tr id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl08" class="StandardFontPlain" align="right" ID="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl08" onmouseout="document.getElementById(&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl08&#39;).style.backgroundColor =  &#39;&#39;;" onmouseover="document.getElementById(&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl08&#39;).style.backgroundColor =  &#39;#daf3f0&#39;;">
                                       <td>يستمع إلى بعض القصص القرآنية التي تشير إلى فضائل وقيم سامية مثل (الصدق، الأمانة، العفو ...)</td><td align="center" onclick="ChangeThisImagesURL(&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit&#39;,&#39;rblSkillResultIDs&#39;,&#39;imgSkillResult&#39;,&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl08_imgSkillResult&#39;);" style="width:280px;"><img id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl08_imgSkillResult" title="أتقن" SkillID="710727" RowIndex="6" hdnSrc="~/images/Common/True.png" src="../images/Common/True.png" style="height:20px;width:20px;border-width:0px;" /></td><td align="center" style="width:400px;"><input name="ctl00$PlaceHolderMain$gvInsertSkillByStudentAndUnit$ctl08$tbTeacherNotes" type="text" maxlength="255" id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl08_tbTeacherNotes" class="StandardFontPlain" style="width:400px;" /></td>
                               </tr><tr id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl09" class="StandardFontPlain" align="right" ID="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl09" onmouseout="document.getElementById(&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl09&#39;).style.backgroundColor =  &#39;&#39;;" onmouseover="document.getElementById(&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl09&#39;).style.backgroundColor =  &#39;#daf3f0&#39;;">
                                       <td>يسمّع السور القرآنية  القصيرة  ( النصر ،الكوثر ، قريش ، الفيل ، القارعة، الشرح ، الماعون)</td><td align="center" onclick="ChangeThisImagesURL(&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit&#39;,&#39;rblSkillResultIDs&#39;,&#39;imgSkillResult&#39;,&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl09_imgSkillResult&#39;);" style="width:280px;"><img id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl09_imgSkillResult" title="أتقن" SkillID="710716" RowIndex="7" hdnSrc="~/images/Common/True.png" src="../images/Common/True.png" style="height:20px;width:20px;border-width:0px;" /></td><td align="center" style="width:400px;"><input name="ctl00$PlaceHolderMain$gvInsertSkillByStudentAndUnit$ctl09$tbTeacherNotes" type="text" maxlength="255" id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl09_tbTeacherNotes" class="StandardFontPlain" style="width:400px;" /></td>
                               </tr><tr id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl10" class="StandardFontPlain" align="right" ID="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl10" onmouseout="document.getElementById(&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl10&#39;).style.backgroundColor =  &#39;&#39;;" onmouseover="document.getElementById(&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl10&#39;).style.backgroundColor =  &#39;#daf3f0&#39;;">
                                       <td>يسمّع بعض الأحاديث النبوية الشريفة المتعلقة بمحتوى المنهج</td><td align="center" onclick="ChangeThisImagesURL(&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit&#39;,&#39;rblSkillResultIDs&#39;,&#39;imgSkillResult&#39;,&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl10_imgSkillResult&#39;);" style="width:280px;"><img id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl10_imgSkillResult" title="أتقن" SkillID="710720" RowIndex="8" hdnSrc="~/images/Common/True.png" src="../images/Common/True.png" style="height:20px;width:20px;border-width:0px;" /></td><td align="center" style="width:400px;"><input name="ctl00$PlaceHolderMain$gvInsertSkillByStudentAndUnit$ctl10$tbTeacherNotes" type="text" maxlength="255" id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl10_tbTeacherNotes" class="StandardFontPlain" style="width:400px;" /></td>
                               </tr><tr id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl11" class="StandardFontPlain" align="right" ID="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl11" onmouseout="document.getElementById(&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl11&#39;).style.backgroundColor =  &#39;&#39;;" onmouseover="document.getElementById(&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl11&#39;).style.backgroundColor =  &#39;#daf3f0&#39;;">
                                       <td>يصف المناسبات الدينية(شهر رمضان - فريضة الحج - عيد الفطر- عيد الأضحى )</td><td align="center" onclick="ChangeThisImagesURL(&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit&#39;,&#39;rblSkillResultIDs&#39;,&#39;imgSkillResult&#39;,&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl11_imgSkillResult&#39;);" style="width:280px;"><img id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl11_imgSkillResult" title="أتقن" SkillID="710721" RowIndex="9" hdnSrc="~/images/Common/True.png" src="../images/Common/True.png" style="height:20px;width:20px;border-width:0px;" /></td><td align="center" style="width:400px;"><input name="ctl00$PlaceHolderMain$gvInsertSkillByStudentAndUnit$ctl11$tbTeacherNotes" type="text" maxlength="255" id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl11_tbTeacherNotes" class="StandardFontPlain" style="width:400px;" /></td>
                               </tr><tr id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl12" class="StandardFontPlain" align="right" ID="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl12" onmouseout="document.getElementById(&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl12&#39;).style.backgroundColor =  &#39;&#39;;" onmouseover="document.getElementById(&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl12&#39;).style.backgroundColor =  &#39;#daf3f0&#39;;">
                                       <td>يصف بعض جوانب أخلاق النبي صلى الله عليه وسلم  وأصحابه</td><td align="center" onclick="ChangeThisImagesURL(&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit&#39;,&#39;rblSkillResultIDs&#39;,&#39;imgSkillResult&#39;,&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl12_imgSkillResult&#39;);" style="width:280px;"><img id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl12_imgSkillResult" title="أتقن" SkillID="710726" RowIndex="10" hdnSrc="~/images/Common/True.png" src="../images/Common/True.png" style="height:20px;width:20px;border-width:0px;" /></td><td align="center" style="width:400px;"><input name="ctl00$PlaceHolderMain$gvInsertSkillByStudentAndUnit$ctl12$tbTeacherNotes" type="text" maxlength="255" id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl12_tbTeacherNotes" class="StandardFontPlain" style="width:400px;" /></td>
                               </tr><tr id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl13" class="StandardFontPlain" align="right" ID="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl13" onmouseout="document.getElementById(&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl13&#39;).style.backgroundColor =  &#39;&#39;;" onmouseover="document.getElementById(&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl13&#39;).style.backgroundColor =  &#39;#daf3f0&#39;;">
                                       <td>يطبق  خطوات الصلاة</td><td align="center" onclick="ChangeThisImagesURL(&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit&#39;,&#39;rblSkillResultIDs&#39;,&#39;imgSkillResult&#39;,&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl13_imgSkillResult&#39;);" style="width:280px;"><img id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl13_imgSkillResult" title="أتقن" SkillID="710724" RowIndex="11" hdnSrc="~/images/Common/True.png" src="../images/Common/True.png" style="height:20px;width:20px;border-width:0px;" /></td><td align="center" style="width:400px;"><input name="ctl00$PlaceHolderMain$gvInsertSkillByStudentAndUnit$ctl13$tbTeacherNotes" type="text" maxlength="255" id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl13_tbTeacherNotes" class="StandardFontPlain" style="width:400px;" /></td>
                               </tr><tr id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl14" class="StandardFontPlain" align="right" ID="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl14" onmouseout="document.getElementById(&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl14&#39;).style.backgroundColor =  &#39;&#39;;" onmouseover="document.getElementById(&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl14&#39;).style.backgroundColor =  &#39;#daf3f0&#39;;">
                                       <td>يطبّق خطوات الوضوء</td><td align="center" onclick="ChangeThisImagesURL(&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit&#39;,&#39;rblSkillResultIDs&#39;,&#39;imgSkillResult&#39;,&#39;ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl14_imgSkillResult&#39;);" style="width:280px;"><img id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl14_imgSkillResult" title="أتقن" SkillID="710722" RowIndex="12" hdnSrc="~/images/Common/True.png" src="../images/Common/True.png" style="height:20px;width:20px;border-width:0px;" /></td><td align="center" style="width:400px;"><input name="ctl00$PlaceHolderMain$gvInsertSkillByStudentAndUnit$ctl14$tbTeacherNotes" type="text" maxlength="255" id="ctl00_PlaceHolderMain_gvInsertSkillByStudentAndUnit_ctl14_tbTeacherNotes" class="StandardFontPlain" style="width:400px;" /></td>
                               </tr><tr class="tableFooterCell">
                                       <td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
                               </tr>
                       </table><table style="width:100%;" border="0">
                               <tr align="Left">
                                       <td align="Left"><span class="StandardFont">عدد السجلات الكلي: 13</span></td>
                               </tr>
                       </table>
  
               </div></td>
       </tr>
  </table>
  |76|updatePanel|ctl00_PlaceHolderMain_UpdatePanel8|<span id="ctl00_PlaceHolderMain_lblopResult" class="ValidationClass"></span>|643|updatePanel|ctl00_PlaceHolderMain_UpdatePanel11|<input type="submit" name="ctl00$PlaceHolderMain$ibtnSave" value="حفظ" onclick="return GetImagesPassFlagsValuesAndConfirm(&#39;ستتم عملية حفظ نتائج المهارة للطفل، هل أنت متأكد من الاستمرار؟&#39;,&#39;ctl00_lblMSG&#39;,&#39;ctl00_ibtnYes&#39;,&#39;ctl00_ibtnNo&#39;,&#39;ctl00_ibtnClose&#39;,&#39;ctl00_lblConfirmTitleText&#39;,&#39;تأكيد عملية الحفظ&#39;,&#39;Save&#39;,&#39;450&#39;,&#39;120&#39;,&#39;&#39;);WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$PlaceHolderMain$ibtnSave&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, false))" id="ctl00_PlaceHolderMain_ibtnSave" title="حفظ" class="btnstyle" />|0|hiddenField|__EVENTTARGET||0|hiddenField|
    
`;

const { EditSkillForm, default: Form } = require("../lib/core/form");

const form = new EditSkillForm(
  Form.fromJson({
    action: "dsd",
    weird: {},
    inputs: [],
    actionButtons: [],
  }).html
);

form.updateFromSreachSubmission(data);

console.log(form.toJson());

